package object;

import entity.Entity;
import entity.Projectile;
import main.GamePanel;

import java.awt.*;

public class OBJ_Fireball extends Projectile {

    GamePanel gp; 
    public static final String objName = "Fireball"; 

    public OBJ_Fireball(GamePanel gp) {
        super(gp); // Call to the parent class constructor
        this.gp = gp; // Store the GamePanel

        name = objName; 
        speed = 5; 
        maxLife = 80; // Fireball disappears after 80 frames
        life = maxLife; 
        attack = 3; // Damage dealt by the fireball
        knockBackPower = 5; // Knockback strength of the fireball
        useCost = 1; // Mana cost for using the fireball
        alive = false; // Initial state of the fireball

        getImage(); // Load fireball sprite images
    }

    // load images for fireball's directions
    public void getImage() {
        up1 = setup("/projectile/fireball_up_1", gp.tileSize, gp.tileSize);
        up2 = setup("/projectile/fireball_up_2", gp.tileSize, gp.tileSize);
        down1 = setup("/projectile/fireball_down_1", gp.tileSize, gp.tileSize);
        down2 = setup("/projectile/fireball_down_2", gp.tileSize, gp.tileSize);
        left1 = setup("/projectile/fireball_left_1", gp.tileSize, gp.tileSize);
        left2 = setup("/projectile/fireball_left_2", gp.tileSize, gp.tileSize);
        right1 = setup("/projectile/fireball_right_1", gp.tileSize, gp.tileSize);
        right2 = setup("/projectile/fireball_right_2", gp.tileSize, gp.tileSize);
    }

    // Check enough mana to use the fireball
    public boolean haveResource(Entity user) {
        return user.mana >= useCost; 
    }

    // Subtract mana cost from the user's mana
    public void subtractResource(Entity user) {
        user.mana -= useCost; 
    }
    
    
    // the particles generated by the fireball
    // the color 
    public Color getParticleColor() {
        return new Color(240, 50, 0); // red-orange
    }

    // the size 
    public int getParticleSize() {
        return 10; // pixels
    }

    // the speed
    public int getParticleSpeed() {
        return 1; // pixels per frame
    }

    // the lifespan
    public int getParticleMaxLife() {
        return 20; // in frames
    }
}
